version: "3.7"

services:
  my-prometheus:
    image: prom/prometheus
    ports:
      - 80:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  ping_service:
    image: alpine
    command: ping docker.com
